import pickle

pool_data = [
    {"name": "Sicilian Defense", "fen": "rnbqkbnr/pp1ppppp/8/2p5/4P3/8/PPPP1PPP/RNBQKBNR w KQkq c6 0 2", "analysis": "1. Fight for the center with ...c5. 2. Sharp tactical battles in the Open Sicilian. 3. Focus on the d4 square and queenside counterplay. Black plays for a win."},
    {"name": "Ruy Lopez", "fen": "r1bqkbnr/pppp1ppp/2n5/1B2p3/4P3/5N2/PPPP1PPP/RNBQK2R b KQkq - 1 3", "analysis": "1. Pressures the e5 pawn and develops the bishop. 2. Focus on long-term positional maneuvering. 3. Control of the center is paramount, leading to complex middlegame struggles."},
    {"name": "French Defense", "fen": "rnbqkbnr/pppp1ppp/4p3/8/4P3/8/PPPP1PPP/RNBQKBNR w KQkq - 0 2", "analysis": "1. A solid, counter-attacking opening. 2. Black accepts a cramped position for long-term stability. 3. Focus on the c5 and f6 pawn breaks to challenge White's center."},
    {"name": "Caro-Kann Defense", "fen": "rnbqkbnr/pp1ppppp/2p5/8/4P3/8/PPPP1PPP/RNBQKBNR w KQkq - 0 2", "analysis": "1. Extremely solid response to e4. 2. Prioritizes pawn structure and king safety. 3. Black seeks a favorable endgame, holding key squares like d5. Low risk, high reliability."},
    {"name": "Queens Gambit", "fen": "rnbqkbnr/ppp1pppp/8/3p4/2PP4/8/PP2PPPP/RNBQKBNR b KQkq c3 0 2", "analysis": "1. White offers a pawn to gain central control. 2. Focus on the d5 square and rapid piece development. 3. Leads to classical, structured positions with deep strategic plans."},
    {"name": "Kings Pawn Game", "fen": "rnbqkbnr/pppp1ppp/8/4p3/4P3/8/PPPP1PPP/RNBQKBNR w KQkq - 0 2", "analysis": "1. The classic 1.e4 e5 opening. 2. Fights immediately for central control and opens lines for the bishop and queen. 3. Leads to open, tactical, and dynamic positions."},
    {"name": "Kings Indian Defense", "fen": "rnbqkb1r/pppppp1p/5np1/8/2PP4/8/PP2PPPP/RNBQKBNR w KQkq - 0 3", "analysis": "1. A hypermodern, aggressive defense. 2. Black allows White a big center to attack it later. 3. Leads to sharp, tactical kingside attacks. Key piece is the g7 bishop."},
    {"name": "Nimzo-Indian Defense", "fen": "rnbqk2r/pppp1ppp/4pn2/8/1bPP4/2N5/PP2PPPP/R1BQKBNR w KQkq - 2 4", "analysis": "1. Black pins the c3 knight to prevent e4. 2. Highly strategic, fighting for center control without occupying it immediately. 3. Often results in doubled pawns for White."},
    {"name": "Italian Game", "fen": "r1bqkbnr/pppp1ppp/2n5/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R b KQkq - 3 3", "analysis": "1. Focuses on rapid development and targeting the weak f7 pawn. 2. Leads to either quiet maneuvering (Giuoco Piano) or sharp attacks (Fried Liver). Strong center control."},
    {"name": "Slav Defense", "fen": "rnbqkbnr/pp2pppp/2p5/3p4/2PP4/8/PP2PPPP/RNBQKBNR w KQkq - 0 3", "analysis": "1. Solid defense against the Queen's Gambit. 2. Black supports the d5 pawn without blocking the light-squared bishop. 3. Leads to stable, fundamentally sound positional structures."},
    {"name": "Dutch Defense", "fen": "rnbqkbnr/ppppp1pp/8/5p2/3P4/8/PPP1PPPP/RNBQKBNR w KQkq f6 0 2", "analysis": "1. Immediate challenge to White's center with 1...f5. 2. Black aims for a kingside attack. 3. Leads to unbalanced, risky, and highly dynamic positions. Not for the faint-hearted."},
    {"name": "English Opening", "fen": "rnbqkbnr/pppppppp/8/8/2P5/8/PP1PPPPP/RNBQKBNR b KQkq - 0 1", "analysis": "1. A flank opening starting with 1.c4. 2. Highly flexible, aiming to control d5 from the side. 3. Leads to strategic, slow-burning games, often avoiding deep opening theory."},
    {"name": "Grunfeld Defense", "fen": "rnbqkb1r/pppppp1p/5np1/8/2PP4/2N5/PP2PPPP/R1BQKBNR b KQkq - 2 3", "analysis": "1. Hypermodern play where Black strikes the center immediately with ...d5. 2. White gets a massive pawn center, but Black relentlessly attacks it with pieces. Very sharp."},
    {"name": "Reti Opening", "fen": "rnbqkbnr/pppppppp/8/8/8/5N2/PPPPPPPP/RNBQKB1R b KQkq - 1 1", "analysis": "1. Flexible, hypermodern opening starting with 1.Nf3. 2. White delays committing pawns to the center, choosing to attack Black's setup later. 3. Often transposes into other systems."},
    {"name": "Catalan Opening", "fen": "rnbqkb1r/pppp1ppp/4pn2/8/2PP4/6P1/PP2PP1P/RNBQKBNR b KQkq - 0 3", "analysis": "1. Combines the Queen's Gambit with a kingside fianchetto. 2. White plays for long-term positional pressure using the strong g2 bishop. 3. Very solid and popular among super-GMs."},
    {"name": "Modern Defense", "fen": "rnbqkbnr/pppppp1p/6p1/8/4P3/8/PPPP1PPP/RNBQKBNR w KQkq - 0 2", "analysis": "1. Black fianchettos the bishop on g7 and delays central pawn moves. 2. Invites White to build a large center to counter-attack later. 3. Flexible and counter-punching."},
    {"name": "Scandinavian Defense", "fen": "rnbqkbnr/ppp1pppp/8/3p4/4P3/8/PPPP1PPP/RNBQKBNR w KQkq - 0 2", "analysis": "1. Immediate central challenge with 1...d5. 2. Eliminates White's e4 pawn early. 3. Black often develops the Queen early. 4. Leads to open positions. Simple to learn."},
    {"name": "Scotch Game", "fen": "r1bqkbnr/pppp1ppp/2n5/4p3/3PP3/5N2/PPP2PPP/RNBQKB1R b KQkq d3 0 3", "analysis": "1. White forces open the center immediately with 3.d4. 2. Creates open lines and sharp tactical skirmishes. 3. White avoids the deep theory of the Ruy Lopez."},
    {"name": "Vienna Game", "fen": "rnbqkbnr/pppp1ppp/8/4p3/4P3/2N5/PPPP1PPP/R1BQKBNR b KQkq - 1 2", "analysis": "1. White develops the queenside knight early. 2. Can lead to wild gambits or quiet positional play. 3. Often aims to play f4, launching a kingside attack."},
    {"name": "Alekhine Defense", "fen": "rnbqkb1r/pppppppp/5n2/8/4P3/8/PPPP1PPP/RNBQKBNR w KQkq - 1 2", "analysis": "1. Provocative defense starting with 1...Nf6. 2. Black lures White's pawns forward to overextend them. 3. Highly dynamic, relying on attacking the overstretched white pawn center."},
    {"name": "Kings Gambit", "fen": "rnbqkbnr/pppp1ppp/8/4p3/4PP2/8/PPPP2PP/RNBQKBNR b KQkq f3 0 2", "analysis": "1. White sacrifices the f-pawn to gain total central control and an open f-file. 2. Leads to chaotic, romantic-era attacking chess. 3. Highly aggressive and risky."},
    {"name": "Bishops Opening", "fen": "rnbqkbnr/pppp1ppp/8/4p3/2B1P3/8/PPPP1PPP/RNBQK1NR b KQkq - 1 2", "analysis": "1. Immediate development of the light-squared bishop. 2. Targets the f7 square early. 3. Often transposes to the Vienna or Italian Game. 4. Solid, avoiding early knight commitments."},
    {"name": "Evans Gambit", "fen": "r1bqk1nr/pppp1ppp/2n5/2b1p3/1PB1P3/5N2/P1PP1PPP/RNBQK2R b KQkq b3 0 4", "analysis": "1. An aggressive pawn sacrifice in the Italian Game. 2. White gives up the b-pawn for rapid development and central domination. 3. Creates immense early attacking pressure."},
    {"name": "Danish Gambit", "fen": "rnbqkbnr/pppp1ppp/8/4p3/3PP3/8/PPP2PPP/RNBQKBNR b KQkq d3 0 2", "analysis": "1. White sacrifices one or two pawns for insanely fast development. 2. Both bishops slice through the board towards Black's kingside. 3. Extremely sharp and purely tactical."},
    {"name": "Petrov Defense", "fen": "rnbqkb1r/pppp1ppp/5n2/4p3/4P3/5N2/PPPP1PPP/RNBQKB1R w KQkq - 2 3", "analysis": "1. A symmetrical and rock-solid defense. 2. Black counter-attacks the e4 pawn immediately. 3. Often leads to drawish, symmetrical pawn structures, favored by players wanting safety."},
    {"name": "Philidor Defense", "fen": "rnbqkbnr/ppp2ppp/3p4/4p3/4P3/5N2/PPPP1PPP/RNBQKB1R w KQkq - 0 3", "analysis": "1. Black defends e5 with d6. 2. Very solid but passive. 3. Black accepts a cramped position, aiming for a slow, strategic buildup and avoiding sharp early tactics."},
    {"name": "Chigorin Defense", "fen": "r1bqkbnr/ppp1pppp/2n5/3p4/2PP4/8/PP2PPPP/RNBQKBNR w KQkq - 1 3", "analysis": "1. An aggressive response to the Queen's Gambit. 2. Black develops the knight to c6, breaking the rule of not blocking the c-pawn. 3. Creates immediate central tension."},
    {"name": "Colle System", "fen": "rnbqkbnr/ppp1pppp/8/3p4/3P4/5N2/PPP1PPPP/RNBQKB1R b KQkq - 1 2", "analysis": "1. A universal opening setup for White. 2. Focuses on a solid d4-e3-c3 pawn structure. 3. Aims for a strong e4 pawn break to launch a kingside attack."},
    {"name": "London System", "fen": "rnbqkbnr/pppp1ppp/4p3/8/3P1B2/5N2/PPP1PPPP/RN1QKB1R b KQkq - 1 3", "analysis": "1. A highly systemic opening for White. 2. Extremely solid pyramid pawn structure. 3. Great for players who prefer understanding core concepts over deep theoretical memorization."},
    {"name": "Trompowsky Attack", "fen": "rnbqkb1r/pppppppp/5n2/8/3P4/5B2/PPP1PPPP/RN1QK1NR b KQkq - 2 2", "analysis": "1. White immediately plays Bg5 against 1...Nf6. 2. Aims to double Black's pawns and avoid deep main-line Indian defenses. 3. Leads to original, unbalanced positional struggles."}
]

with open('masterclass_pool.pkl', 'wb') as f:
    pickle.dump(pool_data, f)

print('Successfully created masterclass_pool.pkl with 30 fully analyzed entries.')

